midi:
  port_name: "IAC Driver Bus 1"
  channel: 1
  tempo_change_cc: 20
  rapid_growth_cc: 21
  decrease_cc:     22
  min_tempo_bpm: 50

smoothing:
  window_width: 5
  rapid_growth_threshold_bpm: 5  # Heart rate increase threshold to trigger rapid growth event
  rapid_growth_cooldown_seconds: 10  # Cooldown period in seconds after rapid growth detection before another rapid growth CC can be sent

data_source:
  type: csv  # pulsoid or csv
  csv:
    path: ../heartrate-data/heartrate.csv
